# Generated by Django 5.0.2 on 2024-02-10 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='recipient',
            new_name='responding_agent',
        ),
        migrations.AddField(
            model_name='message',
            name='response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='chat_app.message', verbose_name='Response'),
        ),
    ]
