# Generated by Django 5.0.2 on 2024-02-10 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0002_rename_recipient_message_responding_agent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='responding_agent',
        ),
    ]
